services:
  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - my_shared_network

  redis:
    image: redis:7
    container_name: redis
    command: ["sh", "-c", "redis-server /usr/local/etc/redis/redis.conf --requirepass \"$REDIS_PASSWORD\""]
    restart: always
    volumes:
      - ./compose/redis/redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/data
    networks:
      - my_shared_network

  emqx:
    image: emqx:5.8.8
    container_name: emqx
    restart: always
    ports:
      - "1883:1883"
      - "18083:18083"
    environment:
      - EMQX_NAME=emqx
      - EMQX_NODE__NAME=emqx@emqx
      - EMQX_NODE__COOKIE=supersecretcookie
      - EMQX_CLUSTER__DISCOVERY_STRATEGY=static
      - EMQX_CLUSTER__STATIC__SEEDS=emqx@emqx
      - EMQX_ALLOW_ANONYMOUS="false"
      - EMQX_DASHBOARD__DEFAULT_USERNAME=${EMQX_DASHBOARD_USERNAME}
      - EMQX_DASHBOARD__DEFAULT_PASSWORD=${EMQX_DASHBOARD_PASSWORD}
    volumes:
      - emqx_data:/opt/emqx/data
      - emqx_log:/opt/emqx/log
    networks:
      - my_shared_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  redis_data:
  emqx_data:
  emqx_log:

networks:
  my_shared_network:
    name: my_shared_network
    driver: bridge
